name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: sources
        uses: actions/checkout@v4

      - name: Set up jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21.0.7
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew build --stacktrace
